# Generated by Django 6.0.1 on 2026-02-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_track_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
